package com.example.myapplication;

import androidx.appcompat.app.AppCompatActivity;

import android.content.Context;
import android.content.Intent;
import android.os.Bundle;
import android.view.View;
import android.widget.AdapterView;
import android.widget.GridView;

import java.util.ArrayList;

public class MainActivity extends AppCompatActivity {
    GridView gridView;
    itemAdapter itemAdapter;
    ArrayList<item> items;
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        gridView=findViewById(R.id.GridView);
        items=new ArrayList<>();
        items.add(new item("Vịnh Hạ Long danh lam thắng cảnh nổi tiếng ở Việt Nam","Từ trên cao nhìn xuống vịnh Hạ Long giống như một bức tranh thủy mặc rộng lớn với non nước, con người vô cùng sống động. Vịnh Hạ Long là một tác phẩm tuyệt mỹ của tạo hóa, thiên nhiên tài hoa biến từng đảo đá tĩnh lặng trở nên có hồn, muôn vàn hình dáng yêu kiều, vừa quen vừa lạ với du khách thập phương. Hàng ngàn đảo đá nổi bật trên sóng nước huyền ảo, lung linh trong ánh nắng vàng làm cho mọi thứ trở nên hoành tráng và khỏe khoắn. Đến vịnh bạn sẽ khám phá quần thể nhiều hòn đảo được đặt tên vô cùng thú vị: hòn Rồng giống như rồng đang bay trên mặt nước, hòn Đầu Người như ai đó hướng về bờ biển, hòn Lã Vọng như ông lão ngồi câu cá hay hòn Cánh Buồm giống hai cánh buồm nâu rẽ sóng ra khơi.\n" +
                "\n" +
                "Vịnh Hạ Long là danh lam thắc cảnh Việt Nam chân thực đến kinh ngạc, từng đảo đá trở nên diệu kỳ theo thời gian biến hóa góc cạnh, màu sắc và cả góc nhìn. Tới đây du khách sẽ hòa mình vào không gian đất trời bao la, mênh mông, cảm nhận rõ những hòn đá tưởng chừng tĩnh lặng vô tri nhưng lại rất có hồn và sống động đến lạ.",R.drawable.halong));
        items.add(new item("Đảo Phú Quốc danh lam thắng cảnh Việt Nam","Đảo Phú Quốc là cảnh đẹp thiên nhiên Việt Nam và trở thành địa điểm du lịch thu hút không chỉ du khách trong nước mà còn du khách nước ngoài tới thăm. Hòn đảo Phú Quốc xinh đẹp có tổng diện tích được so sánh tương đương với diện tích của Singapore. Ở Việt Nam, Phú Quốc còn có một tên gọi khác ngắn gọn và nên thơ hơn đó là Đảo Ngọc.\n" +
                "\n" +
                "Phú Quốc- Kiên Giang là hòn đảo lớn của nước ta và lớn nhất trong hệ thống 22 hòn đảo. Một điểm đặc biệt ở Đảo Ngọc xinh đẹp đó là một năm chỉ có hai mùa là mùa mưa và mùa khô. Thông thường mùa khô sẽ kéo dài tháng 10 đến tháng 3 và cũng chính là mùa du lịch tại đây, thời gian này khách du lịch đến Phú Quốc rất đông. Còn lại mùa mưa thì hầu như không có nhiều khách và biển động nguy hiểm cho hoạt động tắm biển.",R.drawable.phuquoc));
        items.add(new item("Hồ Hoàn Kiếm phong cảnh Việt Nam","Không chỉ là cảnh đẹp Việt Nam từ Bắc vào Nam mà hồ Hoàn Kiếm còn là biểu tượng lịch sử, văn hóa, con người của thủ đô Hà Nội. Với vị trí đắc địa nằm tại trung tâm quận Hoàn Kiếm, thuận lợi đến Hàng Ngang, Nhà Thờ, Hàng Bài, Hàng Khay, Tràng Thi và hồ Hoàn Kiếm thu hút khách du lịch quốc tế đến khám phá, tham quan chiêm ngưỡng cảnh đẹp mê hoặc. Đền Ngọc Sơn là một trong những điểm tham quan khi đến hồ Hoàn Kiếm, nằm về phía Bắc của hồ, đền nối bờ bằng cầu Thê Húc đỏ tươi, bao gồm công trình hoài cổ theo thời gian. Còn biểu tượng của hồ Hoàn Kiếm chính là cầu Thê Húc đỏ son chứng kiến Hà Nội phát triển, thịnh vượng và phồng vinh theo thời gian. Hay vườn hoa Lý Thái Tổ giúp du khách có cái nhìn rõ hơn về cuộc sống người dân thủ đô bình yên, khác với sự đông đúc xô bồ quen thuộc.\n" +
                "\n" +
                "Du khách phương xa đến hồ Hoàn Kiếm chọn nghỉ tại khách sạn quanh phố cổ thì chỉ cần dạo bước một chút là đến phố đi bộ, đền Ngọc Sơn,… Còn nếu xa trung tâm thì các phương tiện công cộng ở đây khá phổ biến, các tuyến bus mà bạn có thể tham khảo như số 16, số 14 và số 9. Khoảng 15 đến 20 phút sẽ có một chuyến nên bạn không lo về việc di chuyển nhé.",R.drawable.hoankiem));
        items.add(new item("Chùa Thiên Mụ mang phong cảnh Việt Nam","Danh lam thắng cảnh Việt Nam không thể thiếu được chùa Thiên Mụ hay còn gọi là Linh Mụ, nằm bên bờ sông Hương thơ mộng, ngồi chùa cổ kính thuộc phường Kim Long, tỉnh Thừa Thiên- Huế. Xây dựng từ năm Tân Sửu 1601, đời chúa Nguyễn đầu tiên Nguyễn Hoàng trị vì. Có thể thấy rằng trong suốt chiều dài lịch sử thì chùa Thiên Mụ là ngôi chùa tuổi đời lâu nhất đất cố đô.\n" +
                "\n" +
                "Biểu tượng của ngôi chùa này đó là tháp Phước Duyên. Vị trí phía trước chùa, tháp Phước Duyên cao đến 21 m, xây dựng với 7 tầng khác nhau, mỗi tầng thờ tượng Phật. Và đặc biệt bên trong có cầu thang thiết kế xoắn ốc đi lên tầng cao nhất và đây là nơi đã từng thờ tượng Phật làm bằng vàng. Ngoài tòa tháp này, chùa Thiên Mụ còn sở hữu hệ công trình lớn như điện Quan Âm, điện Địa Tạng, điện Đại Hùng,…",R.drawable.thienmu));
        items.add(new item("Thị trấn Sa Pa cảnh đẹp thiên nhiên Việt Nam","Nhắc đến cảnh đẹp Việt Nam từ Bắc vào Nam thì ai cũng nhớ đến Sa Pa- thị trấn mờ sương nằm phía Tây Bắc nước ta. Độ cao của Sa Pa cao hơn mực nước biển khoảng 1600 mét, cách trung tâm thành phố Lào Cai khoảng 38 km và từ Hà Nội quãng đường 376 km. Thiên nhiên ưu ái ban tặng cho Sa Pa khí hậu mát mẻ quanh năm, nhiệt độ dao động 15 độ C. Vào những ngày mùa hạ, thị trấn Sa Pa có đủ bốn hình thái thời thiết trong một ngày: sáng hơi se se lạnh của mùa xuân, trưa nắng hạ nhẹ nhàng, chiều thêm chút sương chút gió giống như mùa thu và ban đêm chuyển thành mùa đông lạnh giá. Đôi khi vào thời điểm tháng 11 đến tháng 1 hàng năm, du khách lên Sa Pa còn được ngắm tuyết đá băng giá, ngắm nhìn không gian sương mù giăng kín lối.\n" +
                "\n" +
                "Thị trấn Sa Pa là cảnh đẹp Việt Nam nổi tiếng trong và ngoài nước không chỉ nhờ vào đồi núi hùng vĩ như tranh vẽ mà du khách còn được khám phá các làng dân tộc thiểu số, trải nghiệm nếp sống và văn hóa ẩm thực của họ. Đến Sa Pa thì nhớ tham quan đèo Trạm Côn, dãy Fansipan- nóc nhà Đông Dương, Cổng Trời hay ruộng bậc thang nhé.",R.drawable.sapa));
        items.add(new item("Hội An phong cảnh Việt Nam đẹp cổ kính","Cảnh đẹp đất nước Việt Nam, con người giản dị đơn thuần được thể hiện rõ nhất ở phố cổ Hội An. Hội An là phố cổ nên thơ nằm hạ lưu sông Thu Bồn thuộc tỉnh Quảng Nam và ngày càng trở nên nổi tiếng trong giới yêu thích du lịch và nghỉ dưỡng. Ngay khi đặt chân đến phố cổ Hội An, du khách sẽ trải nghiệm không gian truyền thống văn hóa của người Việt. Bạn sẽ tham quan các làng nghề xưa tồn tại suốt quá trình lịch sử lâu dài như làng đúc đồng Phước Kiều, làng gốm Thanh Hà, làng mộc Kim Bồng. Kiểu kiến trúc của Hội An vô cùng cổ kính như miếu Quan Công, hội quán Phúc Kiến, nhà thờ tộc Trần và chùa Cầu. Nếu bạn muốn rời xa thành phố đông đúc, ồn ào và khói bụi thì Hội An sẽ là điểm đến thích hợp để ngắm chìm trong yên tĩnh, dân bản địa thân thiện dễ gần.\n" +
                "\n" +
                "Đêm xuống là lúc những chiếc đèn lồng xinh đẹp sáng đèn trước cửa những ngôi nhà cổ, đặc biệt khi di chuyển bằng thuyền bạn sẽ như xuyên không về quá khứ, cảm nhận một Việt Nam xưa cũ thời ông bà anh. Một Hội An lung linh, ánh đèn khắp mọi nơi cùng ngọn đèn hoa đăng thả nhẹ tên mặt sông khiến tâm hồn thoải mái nhẹ nhàng và thêm yêu cảnh đẹp thiên nhiên nơi đây.\n" +
                "\n",R.drawable.hoian));
        items.add(new item("Phố cổ Hà Nội phong cảnh Việt Nam theo chiều dài lịch sử","Phố cổ Hà Nội là một nét gì đó rất riêng biệt của cảnh đẹp Việt Nam, gợi nhớ về một thủ đô ngàn năm văn hiến cùng cuộc sống con người thay đổi theo thời gian. Tại Hà Nội, phố cổ Hội An nằm tại hồ Hoàn Kiếm, sở hữu 36 phố phường với đặc điểm mỗi phố có một mặt hàng riêng biệt. Từng ngóc ngách phố cổ lưu giữ lịch sử phát triển thủ đô, hấp dẫn mọi du khách tứ phương đến khám phá.\n" +
                "\n" +
                "Cảng đẹp đất nước Việt Nam- phố cổ Hà Nội được giới hạn về phía Đông bởi đường Trần Nhật Duật và Trần Quang Khải, phía Tây- phố Phùng Hưng, phía Nam là Hàng Gai, Hàng Bông, Cầu Gỗ, cuối cùng phía Bắc là phố Hàng Đậu. Từ phố cổ du khách sẽ thuận tiện hơn cho việc tham quan hồ Hoàn Kiếm, đền Ngọc Sơn, chợ Đồng Xuân, phố Hàng Mã, Ô Quan Chưởng,… đậm chất Hà Nội\n" +
                "\n",R.drawable.phocohanoi));
        items.add(new item("Mũi Né danh lam thắng cảnh Việt Nam tuyệt đẹp","Mũi Né- cảnh đẹp thiên nhiên Việt Nam với những bãi biển trải dài trong xanh, cát trắng mịn trải dài, ánh nắng chan hòa tạo nên không gian thơ mộng khiến bao tâm hồn yêu du lịch không khỏi tương tư. Hiện nay du lịch Mũi Né đang trở thành chuyến đi được nhiều gia đình chọn lựa, thu hút lượng khách nước ngoài không nhỏ.\n" +
                "\n" +
                "Nhờ nằm trong vùng khí hậu nhiệt đới nên Mũi Né được tự nhiên ưu ái khi ít khi chịu ảnh phưởng từ gió mùa Đông Bắc, đẹp và hấp dẫn quanh năm. Nhưng khoảng tháng 12 đến tháng 2 thì Mũi Né mát nhất, tháng 4 đến tháng 5 thì thời tiết khá oi nóng. Nên nếu lên kế hoạch du lịch Mũi Né bạn nên chọn thời điểm khoảng tháng 6 hoặc tháng 7 nhé.",R.drawable.muine));
        items.add(new item("Vườn quốc gia Phong Nha- Kẻ Bàng cảnh đẹp thiên nhiên Việt Nam","Danh thắng Việt Nam vườn quốc gia Phong Nha- Kẻ Bàng là không gian du lịch sinh thái, khám phá tự nhiên hấp dẫn thú vị tại tỉnh Quảng Bình. Nếu có cơ hội đến Quảng Bình thì không ai bỏ qua vườn quốc gia Phong Nha- Kẻ Bàng bởi nơi đây nổi tiếng toàn cầu nhờ vào núi non hùng vĩ, hang động sâu hút, làm cho du khách tò mò. Phong cảnh của vườn quốc gia rất tuyệt vời, khiến ai cũng phải thốt lên rằng mẹ thiên nhiên sao có thể tài tình và tuyệt diệu đến như vậy. Phong Nha- Kẻ Bàng mang đất trời gần lại với nhau hơn, núi cao cùng mặt nước hòa quyện khiến cho thời tiết ở đây quanh năm mát mẻ, trong lành và yên bình dành cho ai muốn rời xa cuộc sống đô thị ồn ào và khói bụi.\n" +
                "\n" +
                "Sự hòa quyện giữa sắc xanh ngọc bích của mặt nước, xanh dương nền trời cao cùng hang động kỳ thú nhiều sắc màu chưa được con người khám phá hết tạo nên nét đặc trưng riêng của vườn quốc gia Phong Nha- Kẻ Bàng. Thạch nhũ trong hang động tạo hình hoàn hảo, lấp lánh trong ánh đèn chính là điểm nhấn cho nơi đây. Nhắc đến Phong Nha- Kẻ Bàng, người ta sẽ nhớ đến một trong những cảnh đẹp Việt Nam tuyệt vời nhất Quảng Bình.",R.drawable.phongnha));
        items.add(new item("Nha Trang phong cảnh thiên nhiên đẹp nhất Việt Nam","Nha Trang ở trong danh sách cảnh đẹp Việt Nam nhờ vào cảnh đẹp nức lòng khách du lịch. Thành phố Nha Trang sở hữu vị trí nằm ven biển và cũng là trung tâm kinh tế, chính trị, du lịch và văn hóa phát triển hàng đầu của tỉnh Khánh Hòa và các tỉnh thành duyên hải Nam Trung Bộ nước ta. Vùng biển này còn nổi tiếng với đặc sản yến sào- thực phẩm bổ dưỡng, cao lương mỹ vị chỉ dâng lên vua chúa thời xưa. Được người dân Việt Nam ưu ái đặt tên là “hòn ngọc viễn Đông”, thành phố Nha Trang vừa đem đến không gian thiên nhiên rộng lớn, cảnh quan mát mẻ trong lành nhờ vào bãi biển trong xanh, bãi cát trắng mịn màng dưới ánh nắng vừa có hệ thống đảo ngoài khơi với hệ sinh thái san hô đặc sắc và kỳ ảo. Nổi tiếng nhất tại Nha Trang có lẽ là ngôi đền Chăm rêu phong cổ kính hay bảo tàng tĩnh lặng giữa thành phố sôi động.",R.drawable.nhatrang));
        items.add(new item("Đà Lạt phong cảnh Việt Nam đẹp hiền hòa","Đà Lạt là một thành phố mang theo bao cảnh đẹp Việt Nam bởi sự bình yên nhẹ nhàng như hơi thở, thành phố ngàn hoa, thành phố mộng mơ, xứ sở tình yêu ai cũng muốn khám phá một lần trong đời. Không giống như nhiều địa điểm khác, Đà Lạt đẹp quanh năm, mỗi mùa đến mùa đi lại có nét riêng khiến tâm hồn con người thấy thoải mái.\n" +
                "\n Tháng 2 đến tháng 4 là thời điểm hoa anh đào nở rực rỡ, nhành hoa phượng tím đón nắng đón gió trong gió xuân giúp hồ Xuân Hương thêm lộng lẫy hơn. Hay bạn muốn tìm về một Đà Lạt nắng mưa bất chợi, cảnh đẹp thay đổi thường xuyên thì nên đi vào tháng 8, thác Dambri, thác Pren cũng trở nên hùng vĩ hơn với bọt nước tung trắng xóa.\n" +
                "\n" +
                "Còn dịp cuối năm tháng 10 đến tháng 12, ánh mây bắt đầu tụ họp trên trời khiến không gian ngát xanh. Và thời điểm này hoa dã quỳ bắt đầu nở rộ, hoa mimosa e ấp bên những triền đồi, hoa hướng dương vàng tươi rói, vườn hồng nhung đỏ đầy bí ẩn,… làm cho Đà Lạt nhiều màu sắc khác nhau. Đã đặt chân đến Đà Lạt thì bạn nên khám phá thác Cam Ly, thác Voi, hồ Đa Nhim, hồ Tuyền Lâm, thung lũng tình yêu, núi Langbiang,…",R.drawable.dalat));
        items.add(new item("Cố đô Huế mang đậm chất cảnh đẹp Việt Nam ","Danh thắng Việt Nam nào là biểu tượng cho sức mạnh và uy quyền của một đến chế phong kiến Việt Nam đã tồn tại trong quá khứ. Đó chính là cố đô Huế- cung điện vua chúa vào thế kỷ 19 thời kỳ hưng thịnh nhất của nước ta. Cố đô Huế sở hữu đầy đủ các đặc trưng điển hình quen thuộc và nổi bật của kinh đô phương Đông thời phong kiến, đem lại kiến thức lịch sử hấp dẫn.\n" +
                "\n" +
                "Cố đô Huế bao gồm 16 hạng mục khác nhau nhưng đáng chú ý nhất là Kinh Thành, Tử Cấm Thành, Hoàng Thành, Võ Miếu, lăng tẩm, Văn Miếu, đàn Nam Giao, chùa Thiên Mụ, Hồ Quyền. Đặc biệt là quần thể di tích cố đô Huế được UNESCO công nhận là di sản văn hóa thế giới năm 1993. Nơi đây mang trong mình kiến trúc, thành tựu độc đáo và nghệ thuật truyền thống của người Việt Nam.",R.drawable.codohue));
        items.add(new item("Biển Vũng Tàu phong cảnh Việt Nam nên thơ","Nằm trong danh sách những cảnh đẹp Việt Nam quyến rũ và hấp dẫn nhất, biển Vũng Tàu giúp cho ngành du lịch nước ta trở nên phát triển và gần hơn với bạn bè quốc tế. Biển nơi đây nổi tiếng nhờ vào nước biển trong xanh tươi mát, bãi cát vàng mịn trải dài, gợn sóng lăn tăn, bất kỳ ai đặt chân đến Vũng Tàu cũng có ấn tượng sâu sắc.\n" +
                "\n" +
                "Một điểm thú vị tại biển Vũng Tàu đó chính là trên bãi biển có nhiều hoạt động ngoài trời, giúp bạn vui chơi giải trí tăng cường sức khỏe như chơi bóng chuyền, tắm biển, đi mô tô lướt sóng, chạy ca nô hòa mình cùng sóng nước mùa hè. Vẻ đẹp của Vũng Tàu chính là sự hòa quyện đặc sắc giữa màu xanh dương của nước biển và bầu trời xanh cao tít, ánh nắng dịu nhẹ.",R.drawable.vungtau));
        items.add(new item("Quần thể danh thắng Tràng An","Thắng cảnh Việt Nam- quần thể danh thắng Tràng An đã được tổ chức UNESCO công nhận là di sản thế giới. Chỉ cách Hà Nội khoảng 90 km, Tràng An ngày càng trở nên thu hút du khách trong nước lẫn nước ngoài nghỉ dưỡng, tham quan. Nơi đây giống như vịnh Hạ Long trên cạn cùng 100 hang động, quần thể đầm, hồ, rừng, núi đá vôi chứa đựng giá trị thiên nhiên và văn hóa vô cùng đặc sắc. Trong quần thể Tràng An rộng lớn sở hữu hệ thống khu du lịch như: khu du lịch Tam Cốc, khu sinh thái Tràng An, khu di tích lịch sử cố đô Hoa Lư, rừng nguyên sinh. Rừng đặc dụng Hoa Lư chính là sự liên kết của các khu du lịch sinh thái nằm trên núi đá vôi với sông, đầm, hồ diện tích 12.000 ha. Vẻ đẹp của Tràng An khiến trời đất dung hòa, tạo nên thế giới tự nhiên thú vị mà con người chưa khám phá hết.",R.drawable.trangan));
        items.add(new item("Chùa Bái Đính cảnh đẹp Việt Nam đậm chất tâm linh","Chùa Bái Đính là cảnh đẹp Việt Nam mang ý nghĩa tâm linh sâu sắc, đây là quần thể chùa nằm tại núi Bái Đính, Gia Sinh thuộc huyện Gia Viên. Nếu đi từ cố đô Hoa Lư đến chùa thì khoảng 5 km, còn từ Ninh Bình là 12 km. Khuôn viên ngôi chùa rộng đến 539 ha gồm chùa mới và chùa cổ gắn liền với 1000 năm triều đại phong kiến nhà Tiền Lê, nhà Đinh và nhà Lý. Về tổng thể, ngôi chùa Bái Đính mang trong hình kiến trúc quy chuẩn quen thuộc của kiến trúc chùa cổ đậm chất Việt Nam. Đặc biệt ngôi chùa mới xây dựng đồ sộ, mái tòa chính điện vô cùng công phu gồm 3 tầng và 12 mái công, mái lợp hình mũi hài và bậc thềm trang trí rồng đá thời Lý, sân rộng tầm nhìn xuống giếng Ngọc.\n" +
                "\n" +
                "Đến chùa Bái Đính, du khách hãy ưu tiên tham quan một số địa điểm hấp dẫn đi kèm nhiều câu truyện cổ xưa huyền bí: đền thờ thánh Nguyễn, giếng Ngọc, hang sáng, động tối. Trong khuôn viên chùa Bái Đính trồng nhiều cây xanh, nhất là cây bồ đề, không gian thanh tịnh thích hợp cho chư tôn tăng ni phật tử đến tu tập và chiêm bái.",R.drawable.chuabaidinh));
        items.add(new item("Vườn quốc gia Cúc Phương- thắng cảnh Việt Nam","Một điều khiến Cúc Phương đặc biệt đó là hiện đang bảo tồn nhiều loại động vật- thực vật có trong sách đỏ, nguy cơ tuyệt chủng cao, điển hình như vooc mông đen trắng. Thời điểm phù hợp nhất đến vườn Cúc Phương là mùa khô tháng 12 đến tháng 5, khí hậu mát mẻ phù hợp để vui chơi. Và tháng 5 là thời điểm bước rừng về đây khoe sắc ngợp trời, giống như chốn thần tiên tuyệt đẹp.\n" +
                "\n" +
                "Vườn quốc gia Cúc Phương cũng có nhiều địa điểm tham quan thú vị như động người xưa, hang Con Moong, động Trăng Khuyết, đỉnh Mây Bạc, hồ Yên Quang, động Phò Mã hay bản Mường. Thiên nhiên ban tặng cho Cúc Phương không gian non nước mây trời hữu tình và còn nhiều điều con người chưa khám phá được hết.",R.drawable.vuoncucphuong));
        items.add(new item("Nhà hát lớn Hà Nội","Nhà hát lớn Hà Nội là nơi mang đậm dấu ấn lịch sử của thủ đô và nay trở thành nơi tổ chức ca nhạc, biểu diễn nghệ thuật của các ca sĩ, nghệ sĩ hàng đầu. Muốn chiêm ngưỡng vẻ đẹp kiến trúc kiểu Pháp của nhà hát lớn thì bạn nên mua vé thưởng thức chương trình biểu diễn, như vậy mới cảm nhận rõ nhất vẻ tráng lệ, cổ kính của nơi đây.",R.drawable.nhahatlon));
        items.add(new item("Chùa Một Cột","Chùa Một Cột là danh lam thắng cảnh Việt Nam nằm giữa thủ đô, gần với bảo tàng Hồ Chí Minh và là di tích lịch sử văn hóa- biểu tượng Hà Nội nghìn năm văn hiến. Nơi đây còn có tên gọi khác là Liên Hoa Đài hay Diên Hự Tự mang lối kiến trúc xây dựng độc đáo, hình vuông nằm trên cột đá vững chắc khiến chùa Một Cột trở thành điểm du lịch nổi tiếng của thành phố. Ngôi chùa nhỏ nổi trên mặt hồ vô cùng độc đáo nhờ vào hệ thống thanh gỗ rắn chắc tạo nên cấu trúc bền bỉ theo năm tháng, hỗ trợ cho tòa thắp đững vứng giống như bông sen mọc lên giữa hồ. Kiến trúc của chùa là hình vuông gỗ, cạnh dài 3 m, mái cong bao phỉ, phía trên có lưỡng long chầu nguyệt. Qua nhiều năm, chùa Một Cột cũng trải qua phục hồi, cải tạo nhiều lần và là một phần của chùa Diên Hựu ngày xưa.",R.drawable.chuamotcot));
        items.add(new item("Cầu quay sông Hàn- phong cảnh Việt Nam hiện đại","Đà Nẵng là một thành phố xinh đẹp và được đánh giá là nơi đáng sống nhất tại Việt Nam. Nhắc đến cảnh đẹp Việt Nam tại Đà Nẵng thì ai ai cũng nhớ đến ngay cầu quay sông Hàn- biểu tượng của thành phố xinh đẹp đang trên đà phát triển. Ban ngày hay ban đêm cầu sông Hàn đều đẹp nhưng có lẽ khung cảnh sẽ tuyệt vời nhất vào buổi tối, mọi thứ trở nên huyền ảo và lung linh.\n" +
                "\n" +
                "Còn gì hoàn hảo hơn khi cùng người thương dành một khoảng thời gian đi du lịch Đà Nẵng để dạo bước trên cầu, ngắm nhìn sông Hàn rộng lớn lung linh nhờ ánh đèn nhiều màu sắc của thành phố. Đà Nẵng về đêm đẹp một cách rất khác biệt, không gian yên bình, dễ chịu và thơ mộng, đặc biệt từ góc nhìn của cầu quay sông Hàn.\n" +
                "\n",R.drawable.causonghan));
        itemAdapter = new itemAdapter(this,R.layout.row_item,items);
        gridView.setAdapter(itemAdapter);
        gridView.setOnItemClickListener(new AdapterView.OnItemClickListener() {
            @Override
            public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
                Intent intent=new Intent(MainActivity.this,Details.class);
                intent.putExtra("title",items.get(position).getTitle());
                intent.putExtra("image",items.get(position).getImage());
                intent.putExtra("text",items.get(position).getText());
                startActivity(intent);
            }
        });

    }
}